/**
 * Notification documents for `allSchema.seeder.js`.
 * The first 13 entries (indices 0–12) match `notif1` … `notif13` in the user-notification seed.
 */
export function buildNotificationSeedDocuments({
  now,
  superAdmin,
  operator1,
  operator2,
  terminalAdmin1,
  terminalAdmin2,
  bus1,
  bus2,
  bus3,
  bus4,
  bus5,
  bus6,
  bus7,
  bus8,
  bus9,
  bus10,
  bus11,
  bus12,
  bus13,
  route01A,
  route02B,
  route03C,
  route04D,
  route05E,
  route06F,
  route07G,
  smTerminal,
  ayalaTerminal,
  carbonTerminal,
  itParkTerminal,
  mandaueTerminal,
  southBusTerminal,
  waterfrontTerminal,
}) {
  const ago = (ms) => new Date(now.getTime() - ms);
  const H = 60 * 60 * 1000;
  const M = 60 * 1000;

  return [
    {
      sender_id: superAdmin._id,
      bus_id: null,
      route_id: null,
      terminal_id: null,
      title: "System Maintenance Notice",
      message:
        "The bus tracking system will undergo maintenance on March 31, 2026 from 2:00 AM to 4:00 AM. Real-time tracking may be temporarily unavailable.",
      notification_type: "info",
      priority: "high",
      scope: "system",
      createdAt: ago(2 * H),
    },
    {
      sender_id: operator1._id,
      bus_id: bus1._id,
      route_id: route01A._id,
      terminal_id: null,
      title: "Bus CEB-001 Delayed",
      message:
        "Bus CEB-001 on Route 01A (SM to Ayala) is running 6 minutes behind schedule due to heavy traffic on Mango Avenue.",
      notification_type: "delay",
      priority: "medium",
      scope: "bus",
      createdAt: ago(30 * M),
    },
    {
      sender_id: operator1._id,
      bus_id: bus1._id,
      route_id: route01A._id,
      terminal_id: null,
      title: "Bus CEB-001 at Full Capacity",
      message:
        "Bus CEB-001 is currently at full capacity (50/50 passengers). Please wait for the next bus or consider alternative routes.",
      notification_type: "full",
      priority: "medium",
      scope: "bus",
      createdAt: ago(15 * M),
    },
    {
      sender_id: operator2._id,
      bus_id: null,
      route_id: route02B._id,
      terminal_id: null,
      title: "Route 02B Service Update",
      message:
        "Additional buses have been deployed on Route 02B (Carbon to Mandaue) due to high demand during rush hour.",
      notification_type: "info",
      priority: "low",
      scope: "route",
      createdAt: ago(1 * H),
    },
    {
      sender_id: operator1._id,
      bus_id: bus1._id,
      route_id: route01A._id,
      terminal_id: null,
      title: "Stop Skipped - Mango Square",
      message:
        "Bus CEB-001 has skipped Mango Square stop due to road construction. The bus will resume normal stops at Capitol Site.",
      notification_type: "skipped_stop",
      priority: "high",
      scope: "bus",
      createdAt: ago(45 * M),
    },
    {
      sender_id: terminalAdmin1._id,
      bus_id: null,
      route_id: null,
      terminal_id: smTerminal._id,
      title: "SM Terminal Parking Update",
      message:
        "Bay 3 and Bay 4 at SM Terminal are temporarily closed for repairs. Buses will use alternative bays.",
      notification_type: "info",
      priority: "medium",
      scope: "terminal",
      createdAt: ago(3 * H),
    },
    {
      sender_id: operator2._id,
      bus_id: bus3._id,
      route_id: route03C._id,
      terminal_id: null,
      title: "Bus CEB-003 Minor Delay",
      message:
        "Bus CEB-003 on Route 03C (IT Park to SM) experienced a 2-minute delay but has now completed its trip.",
      notification_type: "delay",
      priority: "low",
      scope: "bus",
      createdAt: ago(4 * H),
    },
    {
      sender_id: superAdmin._id,
      bus_id: null,
      route_id: route05E._id,
      terminal_id: null,
      title: "Route 05E Schedule Change",
      message:
        "Starting April 1, 2026, Route 05E will have updated departure times. First bus at 6:00 AM, last bus at 10:00 PM.",
      notification_type: "info",
      priority: "high",
      scope: "route",
      createdAt: ago(24 * H),
    },
    {
      sender_id: operator1._id,
      bus_id: bus5._id,
      route_id: null,
      terminal_id: null,
      title: "Bus CEB-005 Maintenance Complete",
      message:
        "Bus CEB-005 has completed scheduled maintenance and will resume service tomorrow morning.",
      notification_type: "info",
      priority: "low",
      scope: "bus",
      createdAt: ago(6 * H),
    },
    {
      sender_id: terminalAdmin2._id,
      bus_id: null,
      route_id: null,
      terminal_id: ayalaTerminal._id,
      title: "Ayala Terminal High Traffic",
      message:
        "Ayala Terminal is experiencing higher than usual foot traffic. Please allow extra time for boarding.",
      notification_type: "info",
      priority: "medium",
      scope: "terminal",
      createdAt: ago(20 * M),
    },
    {
      sender_id: superAdmin._id,
      bus_id: null,
      route_id: null,
      terminal_id: null,
      title: "Peak Season Travel Advisory",
      message:
        "Expect heavier passenger volume on provincial and mall-linked routes this weekend. Arrive at terminals at least 15 minutes before departure.",
      notification_type: "info",
      priority: "medium",
      scope: "system",
      createdAt: ago(5 * H),
    },
    {
      sender_id: operator1._id,
      bus_id: null,
      route_id: route06F._id,
      terminal_id: null,
      title: "Route 06F Extra Morning Trip",
      message:
        "An additional southbound trip on Route 06F (South Bus to SM) departs at 5:45 AM on weekdays until further notice.",
      notification_type: "info",
      priority: "medium",
      scope: "route",
      createdAt: ago(90 * M),
    },
    {
      sender_id: operator1._id,
      bus_id: bus9._id,
      route_id: route02B._id,
      terminal_id: null,
      title: "Bus CEB-009 On Schedule",
      message:
        "Bus CEB-009 on Route 02B is on time for tomorrow's 2:00 PM departure from Carbon Market Terminal.",
      notification_type: "info",
      priority: "low",
      scope: "bus",
      createdAt: ago(10 * M),
    },

    {
      sender_id: operator1._id,
      bus_id: bus6._id,
      route_id: route04D._id,
      terminal_id: null,
      title: "Arrival Reported — CEB-006",
      message:
        "Bus CEB-006 reported arrival at Carbon Market terminal; dispatch is verifying the timestamp.",
      notification_type: "arrival_reported",
      priority: "low",
      scope: "bus",
      createdAt: ago(8 * M),
    },
    {
      sender_id: terminalAdmin2._id,
      bus_id: bus7._id,
      route_id: route03C._id,
      terminal_id: smTerminal._id,
      title: "Arrival Confirmed — CEB-007",
      message:
        "Bus CEB-007 arrival at SM City Cebu Terminal has been confirmed on schedule.",
      notification_type: "arrival_confirmed",
      priority: "low",
      scope: "terminal",
      createdAt: ago(22 * M),
    },
    {
      sender_id: operator2._id,
      bus_id: bus8._id,
      route_id: route05E._id,
      terminal_id: null,
      title: "Departure Reported — CEB-008",
      message:
        "Driver reported departure from Mandaue Terminal for Route 05E; passengers may track live ETA.",
      notification_type: "departure_reported",
      priority: "medium",
      scope: "bus",
      createdAt: ago(35 * M),
    },
    {
      sender_id: operator1._id,
      bus_id: bus11._id,
      route_id: route07G._id,
      terminal_id: waterfrontTerminal._id,
      title: "Departure Confirmed — CEB-011",
      message:
        "Shuttle CEB-011 departure from Waterfront Lahug Terminal has been confirmed.",
      notification_type: "departure_confirmed",
      priority: "low",
      scope: "bus",
      createdAt: ago(50 * M),
    },
    {
      sender_id: operator2._id,
      bus_id: bus12._id,
      route_id: route07G._id,
      terminal_id: null,
      title: "Shuttle 07G Running Late",
      message:
        "Bus CEB-012 on Route 07G is approximately 8 minutes behind due to road work on Salinas Drive.",
      notification_type: "delay",
      priority: "medium",
      scope: "bus",
      createdAt: ago(18 * M),
    },
    {
      sender_id: operator1._id,
      bus_id: bus4._id,
      route_id: route03C._id,
      terminal_id: null,
      title: "Bus CEB-004 Near Capacity",
      message:
        "Bus CEB-004 on Route 03C is at 90% capacity; consider the following trip if you need a seat.",
      notification_type: "full",
      priority: "low",
      scope: "bus",
      createdAt: ago(55 * M),
    },
    {
      sender_id: operator1._id,
      bus_id: bus2._id,
      route_id: route01A._id,
      terminal_id: null,
      title: "Temporary Skip — Fuente Osmeña",
      message:
        "Bus CEB-002 bypassed Fuente Osmeña stop briefly for traffic management; normal service expected next loop.",
      notification_type: "skipped_stop",
      priority: "medium",
      scope: "bus",
      createdAt: ago(3 * H + 12 * M),
    },
    {
      sender_id: superAdmin._id,
      bus_id: null,
      route_id: null,
      terminal_id: null,
      title: "App Update Available",
      message:
        "A new PasaHero app build improves notification reliability. Update when convenient.",
      notification_type: "info",
      priority: "low",
      scope: "system",
      createdAt: ago(48 * H),
    },
    {
      sender_id: operator2._id,
      bus_id: bus13._id,
      route_id: route02B._id,
      terminal_id: null,
      title: "Operator Note — CEB-013",
      message:
        "Internal: confirm headcount reconciliation for CEB-013 after the evening Carbon run.",
      notification_type: "other",
      priority: "low",
      scope: "bus",
      createdAt: ago(72 * H),
    },
    {
      sender_id: superAdmin._id,
      bus_id: null,
      route_id: null,
      terminal_id: null,
      title: "Holiday Custom Banner",
      message:
        "Custom message: Sinulog weekend — extended hours at major terminals Friday through Sunday.",
      notification_type: "custom",
      priority: "medium",
      scope: "system",
      createdAt: ago(96 * H),
    },
    {
      sender_id: terminalAdmin1._id,
      bus_id: null,
      route_id: null,
      terminal_id: carbonTerminal._id,
      title: "Carbon Market Vendor Lane",
      message:
        "Morning market activity may slow boarding at bays 1–2 until 9:00 AM.",
      notification_type: "info",
      priority: "medium",
      scope: "terminal",
      createdAt: ago(7 * H),
    },
    {
      sender_id: operator2._id,
      bus_id: null,
      route_id: route04D._id,
      terminal_id: null,
      title: "Route 04D Evening Frequency",
      message:
        "Route 04D (Ayala to Carbon) will add one extra trip at 7:30 PM on weekdays this month.",
      notification_type: "info",
      priority: "low",
      scope: "route",
      createdAt: ago(12 * H),
    },
    {
      sender_id: operator1._id,
      bus_id: null,
      route_id: route07G._id,
      terminal_id: null,
      title: "07G Vice-Versa Reminder",
      message:
        "Route 07G operates vice-versa; check direction before boarding at Waterfront or Ayala.",
      notification_type: "info",
      priority: "low",
      scope: "route",
      createdAt: ago(16 * H),
    },
    {
      sender_id: superAdmin._id,
      bus_id: bus10._id,
      route_id: route06F._id,
      terminal_id: null,
      title: "CEB-010 Still Out of Service",
      message:
        "Bus CEB-010 remains out of service; spare capacity on Route 06F is covered by CEB-006 and CEB-012.",
      notification_type: "info",
      priority: "high",
      scope: "bus",
      createdAt: ago(30 * H),
    },
    {
      sender_id: terminalAdmin2._id,
      bus_id: null,
      route_id: null,
      terminal_id: itParkTerminal._id,
      title: "IT Park Evening Crowd",
      message:
        "Higher demand expected 5:00–7:00 PM; queue markers are in place at IT Park Terminal.",
      notification_type: "info",
      priority: "medium",
      scope: "terminal",
      createdAt: ago(25 * M),
    },
    {
      sender_id: operator2._id,
      bus_id: null,
      route_id: null,
      terminal_id: mandaueTerminal._id,
      title: "Mandaue Terminal Weather Advisory",
      message:
        "Light rain may affect boarding times; staff will assist at covered waiting areas.",
      notification_type: "info",
      priority: "low",
      scope: "terminal",
      createdAt: ago(9 * H),
    },
    {
      sender_id: superAdmin._id,
      bus_id: null,
      route_id: null,
      terminal_id: southBusTerminal._id,
      title: "South Bus Terminal Security Check",
      message:
        "Random bag checks may add 2–3 minutes to boarding; plan accordingly for provincial trips.",
      notification_type: "info",
      priority: "medium",
      scope: "terminal",
      createdAt: ago(14 * H),
    },
  ];
}
