import type { DriverProps } from "./_components/drivers/DriverProps";
import type { AssignmentProps } from "./_components/assignmens/AssignmentProps";

export const DRIVERS_STATIC: DriverProps[] = [
  {
    id: "1",
    f_name: "Juan",
    l_name: "Dela Cruz",
    license_number: "DL-2024-001234",
    contact_number: "+63 912 345 6789",
    profile_image: "default.png",
    status: "active",
  },
  {
    id: "2",
    f_name: "Maria",
    l_name: "Santos",
    license_number: "DL-2024-005678",
    contact_number: "+63 917 654 3210",
    profile_image: "default.png",
    status: "active",
  },
  {
    id: "3",
    f_name: "Pedro",
    l_name: "Reyes",
    license_number: "DL-2023-009012",
    contact_number: "+63 918 111 2233",
    profile_image: "default.png",
    status: "active",
  },
  {
    id: "4",
    f_name: "Ana",
    l_name: "Garcia",
    license_number: "DL-2024-003456",
    contact_number: "+63 919 444 5566",
    profile_image: "default.png",
    status: "inactive",
  },
  {
    id: "5",
    f_name: "Roberto",
    l_name: "Mendoza",
    license_number: "DL-2023-007890",
    contact_number: "",
    profile_image: "default.png",
    status: "active",
  },
];

export const ASSIGNMENTS_STATIC: AssignmentProps[] = [
  {
    id: "a1",
    bus_id: "b1",
    driver_id: "1",
    operator_user_id: "op1",
    route_id: "r1",
    driver_name: "Juan Dela Cruz",
    operator_name: "Carlos Reyes",
    bus_number: "BUS-101",
    route_name: "EDSA – Monumento to PITX",
    assignment_status: "active",
    assignment_result: "pending",
    arrival_status: "arrival_pending",
    departure_status: "departed",
    arrival_confirmed_at: null,
    departure_confirmed_at: "2025-02-27T06:30:00",
    last_terminal_log: {
      event_type: "departure",
      event_time: "2025-02-27T06:30:00",
      terminal_name: "PITX",
      log_status: "confirmed",
    },
  },
  {
    id: "a2",
    bus_id: "b2",
    driver_id: "2",
    operator_user_id: "op2",
    route_id: "r2",
    driver_name: "Maria Santos",
    operator_name: "Elena Torres",
    bus_number: "BUS-102",
    route_name: "Commonwealth – Fairview to SM North",
    assignment_status: "active",
    assignment_result: "pending",
    arrival_status: "arrived",
    departure_status: "departure_pending",
    arrival_confirmed_at: "2025-02-27T07:15:00",
    departure_confirmed_at: null,
    last_terminal_log: {
      event_type: "arrival",
      event_time: "2025-02-27T07:15:00",
      terminal_name: "Fairview Terminal",
      log_status: "confirmed",
    },
  },
  {
    id: "a3",
    bus_id: "b3",
    driver_id: "3",
    operator_user_id: "op3",
    route_id: "r1",
    driver_name: "Pedro Reyes",
    operator_name: "Miguel Santos",
    bus_number: "BUS-103",
    route_name: "EDSA – Monumento to PITX",
    assignment_status: "active",
    assignment_result: "completed",
    arrival_status: "arrived",
    departure_status: "departed",
    arrival_confirmed_at: "2025-02-27T08:00:00",
    departure_confirmed_at: "2025-02-27T08:45:00",
    last_terminal_log: {
      event_type: "departure",
      event_time: "2025-02-27T08:45:00",
      terminal_name: "Monumento",
      log_status: "confirmed",
    },
  },
  {
    id: "a4",
    bus_id: "b4",
    driver_id: "4",
    operator_user_id: "op2",
    route_id: "r3",
    driver_name: "Ana Garcia",
    operator_name: "Elena Torres",
    bus_number: "BUS-104",
    route_name: "Quezon Ave – QC Circle to Quiapo",
    assignment_status: "inactive",
    assignment_result: "cancelled",
    arrival_status: "arrival_pending",
    departure_status: "departure_pending",
    arrival_confirmed_at: null,
    departure_confirmed_at: null,
    last_terminal_log: null,
  },
  {
    id: "a5",
    bus_id: "b5",
    driver_id: "5",
    operator_user_id: "op1",
    route_id: "r2",
    driver_name: "Roberto Mendoza",
    operator_name: "Carlos Reyes",
    bus_number: "BUS-105",
    route_name: "Commonwealth – Fairview to SM North",
    assignment_status: "active",
    assignment_result: "pending",
    arrival_status: "arrival_pending",
    departure_status: "departure_pending",
    arrival_confirmed_at: null,
    departure_confirmed_at: null,
    last_terminal_log: null,
  },
];
