// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGeFznwFfmIdI4uLV2gfqTWVBx-ZMW0lg',
    appId: '1:464857061623:web:40d74e8111583f08b85bf2',
    messagingSenderId: '464857061623',
    projectId: 'pasahero-db',
    authDomain: 'pasahero-db.firebaseapp.com',
    databaseURL: 'https://pasahero-db-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pasahero-db.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVARrqYFWIy3i7wajAqKZP3ZqmfYG7sL0',
    appId: '1:464857061623:android:94f8ca9273dd8c3cb85bf2',
    messagingSenderId: '464857061623',
    projectId: 'pasahero-db',
    databaseURL: 'https://pasahero-db-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pasahero-db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcxn_LYdvK6CJ9oM79FKRWk3iRlphB1Ts',
    appId: '1:464857061623:ios:90d87c53761c4bafb85bf2',
    messagingSenderId: '464857061623',
    projectId: 'pasahero-db',
    databaseURL: 'https://pasahero-db-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pasahero-db.firebasestorage.app',
    androidClientId: '464857061623-43gdtivbg77t98g0t1vsti1c6hb5hc96.apps.googleusercontent.com',
    iosClientId: '464857061623-fdg892q0ihjnn37treee1irqgmt9p6k6.apps.googleusercontent.com',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcxn_LYdvK6CJ9oM79FKRWk3iRlphB1Ts',
    appId: '1:464857061623:ios:90d87c53761c4bafb85bf2',
    messagingSenderId: '464857061623',
    projectId: 'pasahero-db',
    databaseURL: 'https://pasahero-db-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pasahero-db.firebasestorage.app',
    androidClientId: '464857061623-43gdtivbg77t98g0t1vsti1c6hb5hc96.apps.googleusercontent.com',
    iosClientId: '464857061623-fdg892q0ihjnn37treee1irqgmt9p6k6.apps.googleusercontent.com',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGeFznwFfmIdI4uLV2gfqTWVBx-ZMW0lg',
    appId: '1:464857061623:web:3ee35d75c0576d01b85bf2',
    messagingSenderId: '464857061623',
    projectId: 'pasahero-db',
    authDomain: 'pasahero-db.firebaseapp.com',
    databaseURL: 'https://pasahero-db-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pasahero-db.firebasestorage.app',
  );
}
